# Data Preprocessing Tools

## Importing the libraries

In [8]:
#-- import [libraryname] as [shortcutname]
import numpy as np
import matplotlib.pyplot as plt        #visualization
import pandas as pd                    #dataframe

## Importing the dataset

### Locating the working directry and dataset

In [40]:
# Import the os module
import os

# Get the current working directory
cwd = os.getcwd()

# Print the current working directory
print("Current working directory: {0}".format(cwd))

# Print the type of the returned object
print("os.getcwd() returns an object of type: {0}".format(type(cwd)))

#Set absolute path
abs_path = 'C:/Users/Nhi/Documents/Udemy-exercises/Machine-learning/'

#Change current working directory
os.chdir(abs_path)

Current working directory: C:\Users\Nhi\Documents\Udemy-exercises\Machine-learning
os.getcwd() returns an object of type: <class 'str'>


### Importing dataset and create entities for ML

In [43]:
#---- Importing dataset

# the dot "." is used when we want to access the attribte function from the library (in this case: panda library)
dataset = pd.read_csv('../Machine-learning/dataset/Data.csv') #create dataframe from pandas


In [44]:
#---- Creatng entities for ML

# [rows,columns] - in Python, lower-bound is included, but upper-bound is not
# ":" stands for all the rows
# "-1" stands for "last column"; ":-1" means all columns, exclude last column
X = dataset.iloc[:, :-1].values

Y = dataset.iloc[:, -1].values

In [5]:
print(X)  #independent variable

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [6]:
print(Y)  # dependent variable

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [11]:
#sklearn library to handle missing datas
from sklearn.impute import SimpleImputer
    #library.module           #Class

In [9]:
#Create instance of class (SimpleImputer) to utilize the tool

#Create object for the class
imputer = SimpleImputer(missing_values=np.nan, strategy = 'mean' )

#apply object (imputer) on the matrix of features
imputer.fit(X[:, 1:3])   # all rows, column age(1), and salary(2)

#replace missing data
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [10]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

In [ ]:
#-- Assign numbers for string characters to access thru dataframe

### Encoding the independent Variable

In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [14]:
# Create object and instances for Country names (index: 0)

#-- ColumnTransformer( transformer argument, remainder argument)
ct = ColumnTransformer(transformers= [('encoder',OneHotEncoder(),[0] )] , remainder= 'passthrough')

#Transform the encodes to X with passing to numpy array
X = np.array(ct.fit_transform(X))

In [15]:
print(X)  #-- Countries are now assigned with unique ID from the 3 new columns created

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [16]:
from sklearn.preprocessing import LabelEncoder

In [17]:
le = LabelEncoder()

Y = le.fit_transform(Y)  #dependent variable does not need numpy array 

In [18]:
print(Y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [ ]:
#-- Training set: train ML on existing obs

#-- Test set: evaluate performance of model on new obs

In [19]:
from sklearn.model_selection import train_test_split

#-- train_test_split(4 arguments: matrix of features, dependent variable, split size, fixed random factor )

#recommended split size: 80% in training, 20% in test set

In [20]:
#creating 4 sets for future ML
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state= 1)

In [21]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [22]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [23]:
print(Y_train)

[0 1 0 0 1 1 0 1]


In [24]:
print(Y_test)

[0 1]


## Feature Scaling

In [ ]:
#-- Scaling variables and features to make sure they all take values in the same scale
# preventing one feature to dominte over the other, prevent ML to neglect the features

#-- 2 techniques for feature scaling

#1: Standardization: substract each value of features by the mean, dividing by the sdev
    # all features will take the standard range (e.g: -1 & +3)
    # work all the time

#2: Nomalization: substract each value of features by minimum of features, dividing by the mode (max-min)
   # all features will be between 0 and 1
   # recommended when there's normal distribution or specific situation

In [25]:
#-- Standardization technique

from sklearn.preprocessing import StandardScaler

In [ ]:
#--- FIT: get the mean and sd of each feature

#--- TRANSFORM: apply the formula to transform te values so all can be in the same scale

In [29]:
sc = StandardScaler()

# We DO NOT have to always apply feature scaling the dummy variable to the matrix of features
# Because Standardization will transform all the features and if our dummy has already taken the standard range, we do not need to

#Thus, we will not standardize country names, but only "Age"(index:3) and "Salary"(index:5)
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])

#Transform test set with the SAME SCALE as the train set:
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [30]:
print(X_train)  #age and salary are transformed between -2:+2

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [31]:
print(X_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
